name: Manually deploy frontend 
on: workflow_dispatch

jobs:
  build:
    name: Force manually deploy production
    runs-on: ubuntu-latest
    steps:
    - name: Remove repo at clone it -> large footprint!
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.QWICT_DEPLOY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/qwict/mainpage
          rm -rf QwictMain
          git clone https://github.com/Qwict/QwictMain.git
          cd QwictMain
          git status
          yarn install
          cp ../persistent/frontend/ecosystem.config.js ./
          yarn build
          pm2 list
          pm2 delete Qwict_mainpage_frontend
          pm2 start ecosystem.config.js --watch --ignore-watch="node_modules"